### 1. Créer le Brouillon (On ne passe que les ID et quantités)
POST http://localhost:3000/api/invoices
Content-Type: application/json

{
  "id_client": 1,
  "lignes": [
    {"id_produit": 1, "quantite": 1},
    {"id_produit": 2, "quantite": 2},
    {"id_produit": 3, "quantite": 1},
    {"id_produit": 4, "quantite": 2}
  ]
}

### 2. Consulter le Brouillon (Prévisualisation)
GET http://localhost:3000/api/invoices/1
Accept: application/json

### 3. VALIDER la facture (Figeage des données à la toute fin)
POST http://localhost:3000/api/invoices/1/validate
Content-Type: application/json

{
  "date_facturation": "2018-07-26"
}

### 4. Consulter la facture Validée
GET http://localhost:3000/api/invoices/1
Accept: application/json